/* 
 * Copyright 2015 Torridity.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.tor.tribes.ui.windows;

import de.tor.tribes.ui.util.StretchIcon;
import de.tor.tribes.util.translation.TranslationManager;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author extremeCrazyCoder
 */
public class LanguageSelection extends javax.swing.JDialog {
    private static Logger logger = LogManager.getLogger("Launcher");
    
    private static final int LANGUAGES_PER_ROW = 5;
    
    private String[] languages;
    private String[] icons;
    private int rows;
    private int columns;
    private String selected;
    private Frame parent;
    
    /**
     * Creates new form LanguageSelection
     */
    public LanguageSelection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        languages = TranslationManager.getLanguages();
        icons = TranslationManager.getLanguageIcons();
        initComponents();
        
        rows = languages.length / LANGUAGES_PER_ROW + 1;
        columns = Math.min(LANGUAGES_PER_ROW, languages.length);
        
        for(int i = 0; i < languages.length; i++) {
            generateLanguageButton(i / LANGUAGES_PER_ROW, i % LANGUAGES_PER_ROW, languages[i], icons[i]);
        }
        pack();
    }
    
    private void generateLanguageButton(int row, int column, String name, String image) {
        final String languageName = name;
        String imgName = "./graphics/country-flag-icons/" + image + ".png";
        
        JButton btn = new JButton(new StretchIcon(imgName));
        btn.setPreferredSize(new Dimension(150, 100));
        btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selected = languageName;
                updateSelection();
            }
        });
        getContentPane().add(btn, new GridBagConstraints(column, row, 1, 1, 1, 1, 0, 1, new Insets(0, 0, 0, 0), 0, 0));
    }
    
    private void updateSelection() {
        TranslationManager.getSingleton().setLanguage(selected);
        this.setVisible(false);
    }
    
    public String getSelected() {
        return selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
