/* 
 * Copyright 2015 Torridity.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.tor.tribes.dssim.ui;

import de.tor.tribes.dssim.model.SimulatorTableModel;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Charon
 */
public class TroopsSaveDialog extends javax.swing.JDialog {

    private final int SAVE_OFF_TYPE = 0;
    private final int SAVE_DEF_TYPE = 1;
    private static TroopsSaveDialog SINGLETON = null;
    private int type = SAVE_OFF_TYPE;

    public static synchronized TroopsSaveDialog getSingleton() {
        if (SINGLETON == null) {
            SINGLETON = new TroopsSaveDialog(DSWorkbenchSimulatorFrame.getSingleton(), true);
        }
        return SINGLETON;
    }

    public void showSaveDefDialog() {
        setTitle("Deff speichern");
        type = SAVE_DEF_TYPE;
        jNameField.setText("MeineDeff");
        jExistingSetups.setModel(new DefaultComboBoxModel(TroopsLoadDialog.getSingleton().getDeffSetups()));
        //jExistingSetups.setSelectedIndex(0);
        setLocationRelativeTo(DSWorkbenchSimulatorFrame.getSingleton());
        setVisible(true);
    }

    public void showSaveOffDialog() {
        setTitle("Off speichern");
        type = SAVE_OFF_TYPE;
        jNameField.setText("MeineOff");
        jExistingSetups.setModel(new DefaultComboBoxModel(TroopsLoadDialog.getSingleton().getOffSetups()));
        //jExistingSetups.setSelectedIndex(0);
        setLocationRelativeTo(DSWorkbenchSimulatorFrame.getSingleton());
        setVisible(true);
    }

    /** Creates new form TroopsSaveDialog */
    TroopsSaveDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jNameField = new javax.swing.JTextField();
        jSaveButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jExistingSetups = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setModal(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Bezeichnung");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        jNameField.setMinimumSize(new java.awt.Dimension(180, 25));
        jNameField.setPreferredSize(new java.awt.Dimension(180, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jNameField, gridBagConstraints);

        jSaveButton.setText("Speichern");
        jSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireCloseEvent(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jSaveButton, gridBagConstraints);

        jButton2.setText("Abbrechen");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireCloseEvent(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jButton2, gridBagConstraints);

        jExistingSetups.setMinimumSize(new java.awt.Dimension(180, 25));
        jExistingSetups.setPreferredSize(new java.awt.Dimension(180, 25));
        jExistingSetups.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fireSetupChangedEvent(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jExistingSetups, gridBagConstraints);

        jLabel2.setText("Überschreiben");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fireCloseEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireCloseEvent
        String name = jNameField.getText();
        if (evt.getSource() == jSaveButton) {
            if (name.length() <= 0) {
                JOptionPane.showMessageDialog(this, "Ungültige Bezeichnung.", "Fehler", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (type == SAVE_OFF_TYPE) {
                //save off
                TroopsLoadDialog.getSingleton().saveOff(name, SimulatorTableModel.getSingleton().getOffTroops());
            } else {
                //save def
                TroopsLoadDialog.getSingleton().saveDeff(name, SimulatorTableModel.getSingleton().getDefTroops());
            }
            JOptionPane.showMessageDialog(this, "Truppen erfolgreich gespeichert.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        setVisible(false);
    }//GEN-LAST:event_fireCloseEvent

    private void fireSetupChangedEvent(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fireSetupChangedEvent
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jNameField.setText((String) jExistingSetups.getSelectedItem());
        }
    }//GEN-LAST:event_fireSetupChangedEvent

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                TroopsSaveDialog dialog = new TroopsSaveDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jExistingSetups;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNameField;
    private javax.swing.JButton jSaveButton;
    // End of variables declaration//GEN-END:variables
}
